name: "Setup"
description: "Setup Build Environment"
inputs:
  node_version:
    required: false
    default: v18.13.0
    description: "node version to use"
  npm_version:
    required: false
    default: 8.19.3
    description: "NPM version to use"
  chrome_snapshot:
    required: false
    default: "885292"
    description: "Release snapshot ID of Chrome"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - run: npm install -g npm@${{ inputs.npm_version }}
      shell: bash

    - run: npm install --no-progress
      shell: bash
