name: Build (developement)

on:
  push:
    branches:
      - "!master"
      - "!main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "task/*"

  workflow_call:
    inputs:
      sha:
        type: string
        required: false
        default: ""
        description: "The commit SHA to check out and build. If not provided defaults to the HEAD commit of the Pull Request."

env:
  AZURE_WEBAPP_NAME: fun-dashboard-web-dev # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DIST_ARTIFACT: dist

jobs:
  build:
    uses: ./.github/workflows/ci.yaml

  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DIST_ARTIFACT }}
          path: ./dist

      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
