name: Build & Deploy (production)

on:
  push:
    branches:
      - "main"
      - "master"

concurrency:
  group: ${{ github.workflow }}

env:
  AZURE_WEBAPP_NAME: fun-dashboard-web-prod # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DIST_ARTIFACT: dist

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  deployProd:
    name: Deploy to Prod
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DIST_ARTIFACT }}
          path: ./dist

      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_SERVICE_NAME_PROD }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
