name: Build (developement)

on:
  push:
    branches:
      - "!master"
      - "!main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "task/*"

  workflow_call:
    inputs:
      sha:
        type: string
        required: false
        default: ""
        description: "The commit SHA to check out and build. If not provided defaults to the HEAD commit of the Pull Request."

env:
  AZURE_WEBAPP_NAME: fun-dashboard-web-dev # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DIST_ARTIFACT: dist

jobs:
  build:
    uses: ./.github/workflows/ci.yaml

    # runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x, 20.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # steps:
    # - name: Checkout
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ inputs.sha || github.event.pull_request.head.sha }}

    # - name: 'Setup'

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test

  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DIST_ARTIFACT }}/fun-dashboard-web
          path: ./dist

      # - name: unzip artifact for deployment
      #   run: unzip release.zip

      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_SERVICE_NAME }}
          # slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}dist/fun-dashboard-web
